/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_renatovarela;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus Pc
 */
public class Lab7_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Lab7_Principal
     */
    
    String nombreArtista;
    public Lab7_Principal() {
        initComponents();
         
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Inicio = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jd_Login = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombreUsuarioAger = new javax.swing.JTextField();
        tf_contrasenaAger = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jd_CrearUsuario = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdc_fecha = new com.toedter.calendar.JDateChooser();
        tf_contrasena = new javax.swing.JTextField();
        tf_Usuario = new javax.swing.JTextField();
        tf_Apellido = new javax.swing.JTextField();
        tf_nombreUsuario = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbb_TipoUser = new javax.swing.JComboBox<>();
        jd_PanelArtista = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_seguidores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Album = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_Canciones = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jd_PanelUsuario = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_AritistaSiguiendo = new javax.swing.JList<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_CancionesGuardadasUsuario = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_playlist = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        musica = new javax.swing.JProgressBar();
        jLabel29 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jd_Playlist = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        tf_PlayList = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jdc_fechacreacion = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        tf_generoMusical = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jd_Canciones = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_nombreCancion = new javax.swing.JTextField();
        tf_Duracion = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jf_ano = new javax.swing.JTextField();
        jd_ListadeCanciones = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_cancionesUser = new javax.swing.JList<>();
        jButton12 = new javax.swing.JButton();
        jd_Album = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        tf_NombredelAlbum = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_anoAlbum = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        ParaEscuchar = new javax.swing.JPopupMenu();
        Escuchar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jd_ListaArtistas = new javax.swing.JDialog();
        jButton20 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_artistas = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton1.setText("Usuario");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Artista");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_InicioLayout = new javax.swing.GroupLayout(jd_Inicio.getContentPane());
        jd_Inicio.getContentPane().setLayout(jd_InicioLayout);
        jd_InicioLayout.setHorizontalGroup(
            jd_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InicioLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jd_InicioLayout.setVerticalGroup(
            jd_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InicioLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jd_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jLabel9.setText("Contrasena");

        jLabel10.setText("Nombre Usuario");

        tf_nombreUsuarioAger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreUsuarioAgerActionPerformed(evt);
            }
        });

        tf_contrasenaAger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_contrasenaAgerActionPerformed(evt);
            }
        });

        jButton4.setText("Ingresar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_LoginLayout = new javax.swing.GroupLayout(jd_Login.getContentPane());
        jd_Login.getContentPane().setLayout(jd_LoginLayout);
        jd_LoginLayout.setHorizontalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(52, 52, 52)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombreUsuarioAger, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(tf_contrasenaAger))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_LoginLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(202, 202, 202))
        );
        jd_LoginLayout.setVerticalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombreUsuarioAger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_contrasenaAger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jButton4)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Crear Usuario");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Usuario");

        jLabel5.setText("Contrasena");

        jLabel6.setText("Fecha Nacimiento");

        jButton3.setText("Agregar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel8.setText("Tipo de Usuario");

        cbb_TipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artista", "Usuario" }));

        javax.swing.GroupLayout jd_CrearUsuarioLayout = new javax.swing.GroupLayout(jd_CrearUsuario.getContentPane());
        jd_CrearUsuario.getContentPane().setLayout(jd_CrearUsuarioLayout);
        jd_CrearUsuarioLayout.setHorizontalGroup(
            jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearUsuarioLayout.createSequentialGroup()
                        .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(67, 67, 67)
                        .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreUsuario)
                            .addComponent(jdc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_contrasena)
                            .addComponent(tf_Usuario)
                            .addComponent(tf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_TipoUser, 0, 104, Short.MAX_VALUE))
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))))
        );
        jd_CrearUsuarioLayout.setVerticalGroup(
            jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jdc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbb_TipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jt_seguidores.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jt_seguidores);

        jt_Album.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jt_Album);

        jt_Canciones.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jt_Canciones);

        jLabel11.setText("Seguidores");

        jLabel12.setText("Agregar Album");

        jLabel13.setText("Canciones");

        jButton7.setText("Agregar Album");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Agergar Cancion");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton19.setText("<-----");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_PanelArtistaLayout = new javax.swing.GroupLayout(jd_PanelArtista.getContentPane());
        jd_PanelArtista.getContentPane().setLayout(jd_PanelArtistaLayout);
        jd_PanelArtistaLayout.setHorizontalGroup(
            jd_PanelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_PanelArtistaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jd_PanelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_PanelArtistaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton7))
                    .addComponent(jLabel12)
                    .addGroup(jd_PanelArtistaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButton19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jd_PanelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(jd_PanelArtistaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jd_PanelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_PanelArtistaLayout.setVerticalGroup(
            jd_PanelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_PanelArtistaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jd_PanelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_PanelArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(jd_PanelArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGroup(jd_PanelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_PanelArtistaLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_PanelArtistaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton19)
                                .addGap(62, 62, 62)))
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jd_PanelUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_AritistaSiguiendo.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_AritistaSiguiendo);

        jd_PanelUsuario.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 395, 364, -1));

        jLabel23.setText("Artistas A los que Sigues");
        jd_PanelUsuario.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 361, -1, -1));

        jLabel24.setText("Lista de Canciones");
        jd_PanelUsuario.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jl_CancionesGuardadasUsuario.setModel(new DefaultListModel());
        jl_CancionesGuardadasUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_CancionesGuardadasUsuarioMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jl_CancionesGuardadasUsuario);

        jd_PanelUsuario.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 302, -1));

        jl_playlist.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_playlist);

        jd_PanelUsuario.getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 95, 353, -1));

        jLabel25.setText("PlayList");
        jd_PanelUsuario.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 61, -1, -1));

        jButton11.setText("Agregar Una PlayList");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jd_PanelUsuario.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 243, -1, -1));

        jButton14.setText("AgregarCanciones");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jd_PanelUsuario.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        jButton15.setText("Seguir Artistas");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jd_PanelUsuario.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 538, -1, -1));

        jButton16.setText("<-----");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jd_PanelUsuario.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));
        jd_PanelUsuario.getContentPane().add(musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 642, 760, 32));

        jLabel29.setText("Cancion");
        jd_PanelUsuario.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 658, -1, -1));

        jButton17.setText("Escuchar Cancion");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        jd_PanelUsuario.getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        jButton18.setText("Escuchar Playlist");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jd_PanelUsuario.getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 243, -1, -1));

        jLabel14.setText("Nombre del Playlist");

        jLabel16.setText("Genero Musica");

        jLabel17.setText("Fecha de Creacion");

        jButton9.setText("Agregar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel18.setText("Playlist");

        javax.swing.GroupLayout jd_PlaylistLayout = new javax.swing.GroupLayout(jd_Playlist.getContentPane());
        jd_Playlist.getContentPane().setLayout(jd_PlaylistLayout);
        jd_PlaylistLayout.setHorizontalGroup(
            jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_PlaylistLayout.createSequentialGroup()
                .addGroup(jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_PlaylistLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton9))
                    .addGroup(jd_PlaylistLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_PlaylistLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdc_fechacreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_generoMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(tf_PlayList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jd_PlaylistLayout.setVerticalGroup(
            jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_PlaylistLayout.createSequentialGroup()
                .addGroup(jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jd_PlaylistLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel15))
                    .addGroup(jd_PlaylistLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_PlayList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18)
                .addGroup(jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_generoMusical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jd_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jdc_fechacreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton9)
                .addGap(67, 67, 67))
        );

        jLabel19.setText("Agregar Cancion");

        jLabel20.setText("Nombre de la Cancion");

        jLabel21.setText("Fecha Creacion");

        jLabel22.setText("Duracion");

        tf_nombreCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreCancionActionPerformed(evt);
            }
        });

        tf_Duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_DuracionActionPerformed(evt);
            }
        });

        jButton10.setText("Agregar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CancionesLayout = new javax.swing.GroupLayout(jd_Canciones.getContentPane());
        jd_Canciones.getContentPane().setLayout(jd_CancionesLayout);
        jd_CancionesLayout.setHorizontalGroup(
            jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CancionesLayout.createSequentialGroup()
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CancionesLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel19))
                    .addGroup(jd_CancionesLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(80, 80, 80)
                        .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(tf_Duracion)
                            .addComponent(jf_ano)))
                    .addGroup(jd_CancionesLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jButton10)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jd_CancionesLayout.setVerticalGroup(
            jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CancionesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel19)
                .addGap(44, 44, 44)
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton10)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jl_cancionesUser.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_cancionesUser);

        jButton12.setText("AgregarCancion");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ListadeCancionesLayout = new javax.swing.GroupLayout(jd_ListadeCanciones.getContentPane());
        jd_ListadeCanciones.getContentPane().setLayout(jd_ListadeCancionesLayout);
        jd_ListadeCancionesLayout.setHorizontalGroup(
            jd_ListadeCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListadeCancionesLayout.createSequentialGroup()
                .addGroup(jd_ListadeCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ListadeCancionesLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ListadeCancionesLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jButton12)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jd_ListadeCancionesLayout.setVerticalGroup(
            jd_ListadeCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListadeCancionesLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton12)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jLabel26.setText("Nombre Del Album");

        jLabel27.setText("Ano de Creacion");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("Album");

        jButton13.setText("Agregar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AlbumLayout = new javax.swing.GroupLayout(jd_Album.getContentPane());
        jd_Album.getContentPane().setLayout(jd_AlbumLayout);
        jd_AlbumLayout.setHorizontalGroup(
            jd_AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AlbumLayout.createSequentialGroup()
                .addGroup(jd_AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AlbumLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jd_AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(77, 77, 77)
                        .addGroup(jd_AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_NombredelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(tf_anoAlbum)))
                    .addGroup(jd_AlbumLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel28)))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AlbumLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(258, 258, 258))
        );
        jd_AlbumLayout.setVerticalGroup(
            jd_AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AlbumLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel28)
                .addGap(53, 53, 53)
                .addGroup(jd_AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_NombredelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_anoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(69, 69, 69))
        );

        Escuchar.setText("Escuchar");
        Escuchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscucharActionPerformed(evt);
            }
        });
        ParaEscuchar.add(Escuchar);

        jMenuItem2.setText("jMenuItem2");
        ParaEscuchar.add(jMenuItem2);

        jButton20.setText("Agregar");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });

        jl_artistas.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(jl_artistas);

        javax.swing.GroupLayout jd_ListaArtistasLayout = new javax.swing.GroupLayout(jd_ListaArtistas.getContentPane());
        jd_ListaArtistas.getContentPane().setLayout(jd_ListaArtistasLayout);
        jd_ListaArtistasLayout.setHorizontalGroup(
            jd_ListaArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListaArtistasLayout.createSequentialGroup()
                .addGroup(jd_ListaArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ListaArtistasLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jButton20))
                    .addGroup(jd_ListaArtistasLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jd_ListaArtistasLayout.setVerticalGroup(
            jd_ListaArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ListaArtistasLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButton20)
                .addGap(106, 106, 106))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setText("Ingresar Al Login");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Crear Un Usuario");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      
           jd_CrearUsuario.setModal(true);
        jd_CrearUsuario.pack();
        jd_CrearUsuario.setLocationRelativeTo(this);
        jd_CrearUsuario.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        DefaultListModel modelo = (DefaultListModel) jl_artistas.getModel(); 
        String nombre;
    String apellido;
    String Usuario;
    String contrasena;
    Date fecha;
    
   nombre = tf_nombreUsuario.getText();
   apellido = tf_Usuario.getText();
   Usuario = tf_Usuario.getText();
   contrasena = tf_contrasena.getText();
   fecha = jdc_fecha.getDate();
   
        if (cbb_TipoUser.getSelectedItem().equals("Artista")) {
            artista = new Artista(nombre, apellido, Usuario, contrasena, fecha);
            modelo.addElement(artista);
            
            personas.add(artista);
            
                   AdministrarArtistas ap = new AdministrarArtistas("./Artista.cbm");
        ap.cargarArchivo();
        ap.setArtistas(artista);
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Amigo guardado exitosamente");
      
            
        } else {

            usuario = new Usuario(nombre, apellido, Usuario, contrasena, fecha);
            personas.add(usuario);

            AdminUsuarios ap = new AdminUsuarios("./Usuario.cbm");
            ap.cargarArchivo();
            ap.setUsuarios(usuario);
            ap.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Amigo guardado exitosamente");
        }

        
  
          
    }//GEN-LAST:event_jButton3MouseClicked

    private void tf_nombreUsuarioAgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreUsuarioAgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreUsuarioAgerActionPerformed

    private void tf_contrasenaAgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_contrasenaAgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_contrasenaAgerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            String nombre;
        for (int i = 0; i < personas.size(); i++) {
            
            nombre =  personas.get(i).getClass().getName();
                System.out.println(nombre);
                
              if (nombre.contains("Artista")) {
                   if (tf_nombreUsuarioAger.getText().equals(((Artista)personas.get(i)).getUsuario()) && tf_contrasenaAger.getText().equals(((Artista)personas.get(i)).getContrasena())  ){
                       nombreArtista = ((Artista)personas.get(i)).getNombre();
                jd_PanelArtista.setModal(true);
        jd_PanelArtista.pack();
        jd_PanelArtista.setLocationRelativeTo(this);
        jd_PanelArtista.setVisible(true);
            }else{
                          System.out.println("no existe::"  + nombre +":::h");
                          
                          System.out.println(((Artista)personas.get(i)).getUsuario());
                          System.out.println(((Artista)personas.get(i)).getContrasena());
                          
                      }
            }
  
             if (nombre.contains("Usuario")) {
                 if (tf_nombreUsuarioAger.getText().equals(((Usuario)personas.get(i)).getUsuario()) && tf_contrasenaAger.getText().equals(((Usuario)personas.get(i)).getContrasena())  ){
                jd_PanelUsuario.setModal(true);
        jd_PanelUsuario.pack();
        jd_PanelUsuario.setLocationRelativeTo(this);
       jd_PanelUsuario.setVisible(true);
            }else{
                              System.out.println("no existe::"  + nombre +":::h");  
                          }
            }
   
             
        
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String nombre;
        for (int i = 0; i < personas.size(); i++) {
            
            nombre =  personas.get(i).getClass().toString();
                System.out.println(nombre);
            
            switch(nombre){
                
                case "Artista":
                      if (tf_nombreUsuario.getText().equals(((Artista)personas.get(i)).getUsuario()) && tf_contrasena.getText().equals(((Artista)personas.get(i)).getContrasena())  ){
                jd_PanelArtista.setModal(true);
        jd_PanelArtista.pack();
        jd_PanelArtista.setLocationRelativeTo(this);
        jd_PanelArtista.setVisible(true);
            }else{
                          System.out.println("no existe::"  + nombre +":::h");
                      }
                    
                    break;
                    
                    
                case "Usuario":
                          if (tf_nombreUsuario.getText().equals(((Usuario)personas.get(i)).getUsuario()) && tf_contrasena.getText().equals(((Usuario)personas.get(i)).getContrasena())  ){
                jd_PanelUsuario.setModal(true);
        jd_PanelUsuario.pack();
        jd_PanelUsuario.setLocationRelativeTo(this);
       jd_PanelUsuario.setVisible(true);
            }else{
                              System.out.println("no existe::"  + nombre +":::h");  
                          }
                    
                    break;
                
                
            }
            
            
          
               
        
        }
        
        
  
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
       
         jd_CrearUsuario.setModal(true);
        jd_CrearUsuario.pack();
        jd_CrearUsuario.setLocationRelativeTo(this);
        jd_CrearUsuario.setVisible(true);
        
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
         jd_Login.setModal(true);
        jd_Login.pack();
       jd_Login.setLocationRelativeTo(this);
        jd_Login.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        DefaultListModel modelo = (DefaultListModel) jl_playlist.getModel();
        
        String nombre;
    String generoMusical;
    Date fecha_creacion;
    int duracion;
    
    nombre = tf_PlayList.getText();
    generoMusical = tf_generoMusical.getText();
    fecha_creacion = jdc_fechacreacion.getDate();
    
    playlist = new PlayList(nombre, generoMusical, fecha_creacion, 0);
    
    
    modelo.addElement(playlist);
    listaPlaylist.add(playlist);
    
    
    
    
    tf_PlayList.setText("");
    tf_generoMusical.setText("");
    jdc_fechacreacion.setDate(new Date());
    
    
    
    /*
    DefaultListModel modelo = (DefaultListModel) jl_personas.getModel();
        
        modelo.addElement(new Personas(tf_nombre2.getText(), (Integer)sp_edad.getValue() , (String)cbo_nacionalidad.getSelectedItem()));
    
    
    DefaultListModel modeloLista = (DefaultListModel)jl_personas.getModel();
            ((Personas)modeloLista.get(jl_personas.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("nombre"));
            jl_personas.setModel(modeloLista);
    */
        
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
         
        jd_Canciones.setModal(true);
        jd_Canciones.pack();
        jd_Canciones.setLocationRelativeTo(this);
        jd_Canciones.setVisible(true);
        
    }//GEN-LAST:event_jButton8MouseClicked

    private void tf_nombreCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreCancionActionPerformed

    private void tf_DuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_DuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_DuracionActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        DefaultListModel modelo = (DefaultListModel) jt_Canciones.getModel();
        DefaultListModel modelo2 = (DefaultListModel) jl_cancionesUser.getModel();
        
        String nombre;
    String nombre_Cancion;
    String ano ;
    
    int duracion;
    
    
    nombre_Cancion = tf_nombreCancion.getText();
    ano = jf_ano.getText() ;
    duracion = Integer.parseInt(tf_Duracion.getText());
    
    cancion = new Cancion(nombre_Cancion, ano, nombreArtista, duracion);
    
    modelo.addElement(cancion);
    listaCanciones.add(cancion);
    modelo2.addElement(cancion);
    
    
    
     
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        jd_Album.setModal(true);
        jd_Album.pack();
        jd_Album.setLocationRelativeTo(this);
        jd_Album.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
          jd_ListadeCanciones.setModal(true);
        jd_ListadeCanciones.pack();
        jd_ListadeCanciones.setLocationRelativeTo(this);
        jd_ListadeCanciones.setVisible(true);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
         DefaultListModel modeloLISTA = (DefaultListModel) jl_playlist.getModel();
        DefaultListModel modeloLISTA2 = (DefaultListModel) jl_CancionesGuardadasUsuario.getModel();
        
        PlayList m = (PlayList)modeloLISTA.getElementAt(jl_playlist.getSelectedIndex());
        m.getCancionesPlaylist().add((Cancion)modeloLISTA2.getElementAt(jl_CancionesGuardadasUsuario.getSelectedIndex()));
        int duracionPlayList = 0;
        for (int i = 0; i < m.getCancionesPlaylist().size(); i++) {
            duracionPlayList+=m.getCancionesPlaylist().get(i).getDuracion();
        }
        
        m.setDuracion(duracionPlayList);
 
        modeloLISTA2.remove(jl_CancionesGuardadasUsuario.getSelectedIndex());
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
       DefaultListModel modeloLISTA = (DefaultListModel) jl_CancionesGuardadasUsuario.getModel();
        DefaultListModel modeloLISTA2 = (DefaultListModel) jl_cancionesUser.getModel();
        
        modeloLISTA.addElement(modeloLISTA2.getElementAt(jl_cancionesUser.getSelectedIndex()));
        
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        jd_Playlist.setModal(true);
        jd_Playlist.pack();
        jd_Playlist.setLocationRelativeTo(this);
        jd_Playlist.setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jl_CancionesGuardadasUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_CancionesGuardadasUsuarioMouseClicked
        if (evt.isMetaDown()) {
            ParaEscuchar.setVisible(true); 
        }
    }//GEN-LAST:event_jl_CancionesGuardadasUsuarioMouseClicked

    private void EscucharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscucharActionPerformed
         
    
         
    }//GEN-LAST:event_EscucharActionPerformed

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        DefaultListModel modeloLISTA = (DefaultListModel) jl_CancionesGuardadasUsuario.getModel();

        Cancion m = (Cancion) modeloLISTA.getElementAt(jl_CancionesGuardadasUsuario.getSelectedIndex());

        
        play = new Play(musica, m.getDuracion() * 1000);
        play.start();
        
        
        int posicion = jl_CancionesGuardadasUsuario.getSelectedIndex();
        
        

  
       
       
     
   
     
      
               
                      
       
        
        //play.setAvanzar(true);
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // TODO add your handling code here:
            DefaultListModel modeloLISTA2 = (DefaultListModel) jl_playlist.getModel();
        
         PlayList m2 = (PlayList)modeloLISTA2.getElementAt(jl_playlist.getSelectedIndex());
         
       // System.out.println(m);
       

         //musica.setMaximum();
        play = new Play(musica, m2.getDuracion()*1000);
        play.start();
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
         DefaultListModel modeloLISTA = (DefaultListModel) jt_Album.getModel();
        DefaultListModel modeloLISTA2 = (DefaultListModel) jt_Canciones.getModel();
        
        Album m = (Album)modeloLISTA.getElementAt(jt_Album.getSelectedIndex());
        m.getCancionesAlbum().add((Cancion)modeloLISTA2.getElementAt(jt_Canciones.getSelectedIndex()));
      
 
        modeloLISTA2.remove(jl_CancionesGuardadasUsuario.getSelectedIndex());
        
        
        
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
       
         jd_ListaArtistas.setModal(true);
        jd_ListaArtistas.pack();
        jd_ListaArtistas.setLocationRelativeTo(this);
        jd_ListaArtistas.setVisible(true);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
       DefaultListModel modeloLISTA = (DefaultListModel) jl_AritistaSiguiendo.getModel();
        DefaultListModel modeloLISTA2 = (DefaultListModel) jl_artistas.getModel();
        
        modeloLISTA.addElement(modeloLISTA2.getElementAt(jl_AritistaSiguiendo.getSelectedIndex()));
    }//GEN-LAST:event_jButton20MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
       DefaultListModel modeloLISTA = (DefaultListModel) jt_Album.getModel();
        String nombre_Album;
        String ano;
       

        nombre_Album = tf_NombredelAlbum.getText();
        ano = tf_anoAlbum.getText();
        
        albumes = new Album(nombre_Album, ano, nombreArtista);
         modeloLISTA.addElement(albumes);
        
        

    
    
    
    }//GEN-LAST:event_jButton13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab7_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab7_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab7_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab7_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab7_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Escuchar;
    private javax.swing.JPopupMenu ParaEscuchar;
    private javax.swing.JComboBox<String> cbb_TipoUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JDialog jd_Album;
    private javax.swing.JDialog jd_Canciones;
    private javax.swing.JDialog jd_CrearUsuario;
    private javax.swing.JDialog jd_Inicio;
    private javax.swing.JDialog jd_ListaArtistas;
    private javax.swing.JDialog jd_ListadeCanciones;
    private javax.swing.JDialog jd_Login;
    private javax.swing.JDialog jd_PanelArtista;
    private javax.swing.JDialog jd_PanelUsuario;
    private javax.swing.JDialog jd_Playlist;
    private com.toedter.calendar.JDateChooser jdc_fecha;
    private com.toedter.calendar.JDateChooser jdc_fechacreacion;
    private javax.swing.JTextField jf_ano;
    private javax.swing.JList<String> jl_AritistaSiguiendo;
    private javax.swing.JList<String> jl_CancionesGuardadasUsuario;
    private javax.swing.JList<String> jl_artistas;
    private javax.swing.JList<String> jl_cancionesUser;
    private javax.swing.JList<String> jl_playlist;
    private javax.swing.JList<String> jt_Album;
    private javax.swing.JList<String> jt_Canciones;
    private javax.swing.JList<String> jt_seguidores;
    private javax.swing.JProgressBar musica;
    private javax.swing.JTextField tf_Apellido;
    private javax.swing.JTextField tf_Duracion;
    private javax.swing.JTextField tf_NombredelAlbum;
    private javax.swing.JTextField tf_PlayList;
    private javax.swing.JTextField tf_Usuario;
    private javax.swing.JTextField tf_anoAlbum;
    private javax.swing.JTextField tf_contrasena;
    private javax.swing.JTextField tf_contrasenaAger;
    private javax.swing.JTextField tf_generoMusical;
    private javax.swing.JTextField tf_nombreCancion;
    private javax.swing.JTextField tf_nombreUsuario;
    private javax.swing.JTextField tf_nombreUsuarioAger;
    // End of variables declaration//GEN-END:variables

   
    Cancion cancion = new  Cancion();
    PlayList playlist = new PlayList();
    Artista artista = new Artista();
    Usuario usuario = new Usuario();
    Album albumes = new Album();
    
    
    //ArrayList
    ArrayList<persona> personas = new ArrayList();
    
     ArrayList<PlayList> listaPlaylist = new ArrayList();
     
      ArrayList<Cancion> listaCanciones = new ArrayList();
      
Play play;

}
